export const zodiacSignsData = {
    en: [
        { name: 'Aries', dates: 'March 21 - April 20', icon: '♈️', sign: 'aries' },
        { name: 'Taurus', dates: 'April 21 - May 20', icon: '♉️', sign: 'taurus' },
        { name: 'Gemini', dates: 'May 21 - June 21', icon: '♊️', sign: 'gemini' },
        { name: 'Cancer', dates: 'June 22 - July 22', icon: '♋️', sign: 'cancer' },
        { name: 'Leo', dates: 'July 23 - August 22', icon: '♌️', sign: 'leo' },
        { name: 'Virgo', dates: 'August 23 - September 22', icon: '♍️', sign: 'virgo' },
        { name: 'Libra', dates: 'September 23 - October 22', icon: '♎️', sign: 'libra' },
        { name: 'Scorpio', dates: 'October 23 - November 21', icon: '♏️', sign: 'scorpio' },
        { name: 'Sagittarius', dates: 'November 22 - December 21', icon: '♐️', sign: 'sagittarius' },
        { name: 'Capricorn', dates: 'December 22 - January 19', icon: '♑️', sign: 'capricorn' },
        { name: 'Aquarius', dates: 'January 20 - February 18', icon: '♒️', sign: 'aquarius' },
        { name: 'Pisces', dates: 'February 19 - March 20', icon: '♓️', sign: 'pisces' },
    ],
    ru: [
        { name: 'Овен', dates: '21 марта - 20 апреля', icon: '♈️', sign: 'aries' },
        { name: 'Телец', dates: '21 апреля - 20 мая', icon: '♉️', sign: 'taurus' },
        { name: 'Близнецы', dates: '21 мая - 21 июня', icon: '♊️', sign: 'gemini' },
        { name: 'Рак', dates: '22 июня - 22 июля', icon: '♋️', sign: 'cancer' },
        { name: 'Лев', dates: '23 июля - 22 августа', icon: '♌️', sign: 'leo' },
        { name: 'Дева', dates: '23 августа - 22 сентября', icon: '♍️', sign: 'virgo' },
        { name: 'Весы', dates: '23 сентября - 22 октября', icon: '♎️', sign: 'libra' },
        { name: 'Скорпион', dates: '23 октября - 21 ноября', icon: '♏️', sign: 'scorpio' },
        { name: 'Стрелец', dates: '22 ноября - 21 декабря', icon: '♐️', sign: 'sagittarius' },
        { name: 'Козерог', dates: '22 декабря - 19 января', icon: '♑️', sign: 'capricorn' },
        { name: 'Водолей', dates: '20 января - 18 февраля', icon: '♒️', sign: 'aquarius' },
        { name: 'Рыбы', dates: '19 февраля - 20 марта', icon: '♓️', sign: 'pisces' },
    ],
};